### RENDER CATEGORIES
GET http://localhost:3000/categories

### RENDER FEATURES
GET http://localhost:3000/features

### RENDER ADDRESSES
GET http://localhost:3000/addresses

##############################################
### USERS
##############################################

### REGISTERING a new user
# If this was sent again, request will fail with code 422
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "test@testing.com",
  "username": "test-user1",
  "password": "test-password1",
  "password_confirmation": "test-password1"
}

### ATTEMPTING to register new user with "@" in username
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "test1@testing.com",
  "username": "test@user1",
  "password": "test-password2",
  "password_confirmation": "test-password2"
}

### SIGN IN with ADMIN EMAIL - updated
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "auth": {
    "signin": "admin@picvic.com.au",
    "password": "adminPic"
  }
}

### SIGN IN with ADMIN USERNAME - updated
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "auth": {
    "signin": "admin",
    "password": "adminPic"
  }
}

### SIGN IN with normal user (no admin priviledge)
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "auth": {
    "signin": "bob",
    "password": "Bpicvic"
  }
}

### SIGN IN with newly created test user (no admin)
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "auth": {
    "signin": "test-user1",
    "password": "test-password1"
  }
}

### POST persistent signed in user with jwt
POST http://localhost:3000/auth/signed_in_user
Content-Type: application/json

{
  "jwt": "eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDE5NzU3NTh9.QtqX_W2e2U23ishBay7Jr3uh11g7-EuFLGW5_AlvA_g"
} 


##############################################
### PARKS
##############################################
### RENDER ALL PARKS LIST; GET
GET http://localhost:3000/parks

### RENDER an individual park (that exists)
GET http://localhost:3000/parks/4

### RENDER an individual park (that DOESN'T exists)
GET http://localhost:3000/parks/99


### CREATE A PARK
### POST a park request without a token or admin
POST http://localhost:3000/parks
Content-Type: application/json
Authorization: "Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NsadE5NTI3Njd9.sAoL5DbYuNDg_3IzDKg8wWPvDqRrLA1cZhAXpCfY19c"

{
  "category_id": 1,
  "feature_id": 2,
  "address_id": 1,
  "name": "This park should be able to post by Bob",
  "cheese": "cheese we wont be able to eat",
  "wine": "red wine we can't drink",
  "latitude": -54.46675,
  "longitude": 27.00203
}

### POST with token and admin privilege
# NB: jwt will need to be updated each time after 1hr
POST http://localhost:3000/parks
Content-Type: application/json
Authorization: "Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDE5ODU1ODh9.DgGgbJx_3H3kdqOR00TmXRLarSepi-kIXWnD5JrDvDU"

{
  "category_id": 2,
  "feature_id": 4,
  "address_id": 3,
  "name": "Eastern Beach",
  "cheese": "Geelong cheese",
  "wine": "Geelong wine",
  "latitude": -54.46675,
  "longitude": 27.00203,
}


### UPDATE PARK
### Update park with PUT with right authorisation (ie. admin)
PUT http://localhost:3000/parks/9
Content-Type: application/json
Authorization: "Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDE5NzU3NTh9.QtqX_W2e2U23ishBay7Jr3uh11g7-EuFLGW5_AlvA_g"

{
  "category_id": 1,
  "feature_id": 2,
  "address_id": 3,
  "name": "REDACTED",
  "cheese": "REDACTED",
  "wine": "REDACTED",
  "latitude": 0,
  "longitude": 0
}

### Updating without authorisation
PUT http://localhost:3000/parks/1
Content-Type: application/json
Authorization: "Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDE5NTI3Njd9.sAoL5DbYuNDg_3IzDKg8wWPvDqRrLA1cZhAXpCfY19c"

{
  "category_id": 1,
  "feature_id": 2,
  "address_id": 3,
  "name": "Name should not be able to be change by normal user",
  "cheese": "A name that has changed",
  "wine": "A wine has changed",
  "latitude": -102.234823,
  "longitude": 123.21314
}


### DELETE a park with authorisation
### NB: if a post is referencing a park that you are deleting, you will encounter InvalidForeignKey violation
DELETE http://localhost:3000/parks/9
Authorization: "Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDE5NzU3NTh9.QtqX_W2e2U23ishBay7Jr3uh11g7-EuFLGW5_AlvA_g"

### DELETE a park with no authorisation or admin
DELETE http://localhost:3000/parks/6
Authorization: "Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2NDE5NTI5NjJ9.1sjyJALClMx7MRabi5tJnk9uoYyIsSYcn_7U557ohTE"

### DELETE a park that does not exist
DELETE http://localhost:3000/parks/100
Authorization: "Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDE5NTI4NjR9.PINJBTdOLF5bpLAyP7I0k5Z3EtxeGtfDmYkFNwQBXkM"




##############################################
### COMMENTS/POSTS
##############################################
### GET POSTS from USERS associated with park
GET http://localhost:3000/parks/1/comments/

### ANOTHER COMMENT FOR ANOTHER PARK
GET http://localhost:3000/parks/2/comments/

### ANOTHER COMMENT FOR ANOTHER PARK
GET http://localhost:3000/parks/3/comments/

### SINGLE COMMENT
GET http://localhost:3000/parks/comments/2

### GET A COMMENT FROM A PARK THAT DOES NOT EXIST
GET http://localhost:3000/parks/comments/100



### DELETE A COMMENT: with right authorisation
DELETE http://localhost:3000/parks/comments/18
Content-Type: application/json
Authorization: "Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDE5NzYyNzN9.1XmTG-SibpEZXRD1NY1zeYQqcm-DNJy97_UCQthQeFM"

### DELETE A COMMENT: without right authorisation or user
DELETE http://localhost:3000/parks/comments/17
Content-Type: application/json
Authorization: "Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2NDE5NzY0NDF9.XPSsF6AC49OHOpoVMu6Rb8lVc7GtAyQoAqg4_OSF8nQ"



### POST a comment without a JWT
POST http://localhost:3000/parks/1/comments
Content-Type: application/json

{ 
  "user_id": 1,
  "park_id": 1,
  "comment": "This will not comment",
  "rating": 5
}


### POST a comment with JWT
POST http://localhost:3000/parks/1/comments
Content-Type: application/json
Authorization: "Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDE5NzYxMTl9.Y7LdV3EfHmbvznE20y_sHK5zh8S_-ECqSFeG-AeVVu0"

{
  "comment": "Bob thinks this park is rad",
  "rating": 5
}

### POST a comment with JWT (again)
POST http://localhost:3000/parks/4/comments
Content-Type: application/json
Authorization: "Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDE5NzQ4Mzh9.KQbPDid-KUSkMZaWYzghG_qWyyTsw-lFCA307dqnLSM"

{
  "comment": "test-user1 thinks this is neat",
  "rating": 5
}

###UPDATE A COMMENT
PATCH http://localhost:3000/parks/comments/15
Content-Type: application/json
Authorization: "Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDE5NzY4MzJ9.b_LJEWf8iN32rUDmeUSQ_lHXTUKe19eyyqOoU1sE_kw"

{
  "comment": "Comment is inappropriate",
  "rating": 2
}




